id: AF7C61060
title: Invocation of the Vidyādhara Gurus
type: translation
pechas:
- I62B5D3CA
- IC0670E06
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:38:04.018732
  last_modified_at: 2023-01-04 11:38:04.018744
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I62B5D3CA/0569: B8A2
  IC0670E06/AB9E: B8A2
